name: nutriAI
description: "AI destekli kişisel beslenme koçu uygulaması"
publish_to: 'none' # private app

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  fl_chart: ^1.0.0
  table_calendar: ^3.0.9
  provider: ^6.1.1
  flutter_tts: ^3.8.5
  avatar_glow: ^2.0.2
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/woman-7165664_1280.jpg
    - assets/logo.png
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    - assets/nutri_bot.png